### ISSUE TITLE
Pokewalker doesnt work unless the user does a reset

### ISSUE THREAD

**Issue by fennectech** [DS-Homebrew/nds-bootstrap#1068]
New 3ds w/ luma3ds 
18.4.0
DSI theme

### Expected behaviour

Pokewalker shoudl just work when launching the game

### Actual behaviour

Pokewalker does not work unless I use start select L R to reset the game

### Steps to reproduce

1.Launch pokemon soul silver with a compatible IR cart (black in this case) 
2.go into pokewalker menu
3.Try to send pokemon or receive gift    It simply doesn't detect it.

In TWiLight Menu++:
Ive disabled slot 1 sd access
Ive set select to Select Menu not DSI theme.
  Are there any other settings that must be set somehow for it to work

**Comment by fennectech** [comment]
Hourray.  Thank you for fixing that :)

**Comment by Epicpkmn11** [comment]
Oh sorry, I merged upstream into my fork as I like to keep it up to date and for some reason GitHub picked that up here

**Comment by fennectech** [comment]
Wait.  Is this issue back?

**Comment by Epicpkmn11** [comment]
It seems Robz reverted that commit and he reopened the issue so I guess so

https://github.com/DS-Homebrew/TWiLightMenu/commit/8aa43f7ea43cb1f08a54fa9bb64c4d471d322d11

**Comment by fennectech** [comment]
Is there a good reason for this?

**Comment by RocketRobz** [comment]
IR still wasn't working for some users.

**Comment by MetalDM** [comment]
My IR wouldn't work at all, as opposed to the previous version(?) requiring a reset

New 3dsxl w/ Luma 10.2.1
Using the DSi theme

Expected Behavior:
Should be able to use the IR port from a supported pokemon cart in slot 1

Actual Behavior:
Doesn't work at all. Tried it with Pokemon Heartgold, Black, and White 2. None of the carts could connect to the pokewalker. Tested the pokewalker itself to make sure it works and it does. Also playing soul silver if that somehow helps

Steps to Reproduce:
1.Launch pokemon soul silver with a compatible IR cart 
2.go into pokewalker menu
3.Try to send pokemon or receive gift It simply doesn't detect it.

In Twighlight Menu ++:
Disabled SD access in Slot-1 (disabled by default anyway)
Tested both latest version and a nightly build (18.5.0 and 7c4654ad)
bootstrap: release (0.36.0) and nightly (05fee5a0)
I tried every combination between those two.
(Sorry if I formatted this wrong)

**Comment by thunder1221sa** [comment]
In the same boat as @MetalDM, any estimate on when this might get fixed @RocketRobz?

**Comment by RocketRobz** [comment]
This is low priority, so no idea.

**Comment by devonberryPDX** [comment]
> This is low priority, so no idea.

Perhaps I could work on it I have some coding experience. What info do you have on how to fix it?

**Comment by RocketRobz** [comment]
Try here: http://problemkaputt.de/gbatek-ds-cart-infrared-pedometers.htm

**Comment by Sonicjan** [comment]
Pokewalker can't connect for me either... I'm using Blaxk 2 as the IR card and tried connecting the Pokewalker with my german HeartGold

**Comment by rayfoster14** [comment]
This feature works perfectly fine for me. Tested with a rip of UK / PAL HeartGold with it's original card inserted and a UK / PAL version of White 2. I can send and receive from the Pokewaller perfectly with no issues when running nds-bootstrap v0.35.1 on my n3dsxl
