### ISSUE TITLE
Wireless play's issues and issues not booting

### ISSUE THREAD

**Issue by KururinX** [DS-Homebrew/nds-bootstrap#1155]
VRAM Boost:default(ON)　DMA Boot:default(ON)

　TWL v20.2.1 + Bootstrap v0.40.2 (DSiLL)
Mario Kart DS (JP) : Freezes when multi-play is selected
Momotarou Dentetsu 20 Shuunen (JP) : not started (White out)
Momotarou Dentetsu Tokyo and Japan (JP) : Download play is possible, but wireless play is not possible
Momotarou Dentetsu World (JP) : not started (Black out)

　TWL v20.2.1 + Bootstrap v0.39.1 (DSiLL)
Mario Kart DS (JP): Freezes when multi-play is selected
Momotarou Dentetsu 20 Shuunen (JP) : Error when multi-play is selected
Momotarou Dentetsu Tokyo and Japan (JP) : Download play is possible, but wireless play is not possible
Momotarou Dentetsu World (JP) : Error when multi-play is selected

　TWL v20.1.0 + Bootstrap v0.40.2 (DSiLL)
Mario Kart DS (JP) :  Freezes when multi-play is selected
Momotarou Dentetsu 20 Shuunen (JP) : not started (White out)
Momotarou Dentetsu Tokyo and Japan (JP) : Download play is possible, but wireless play is freeze
Momotarou Dentetsu World (JP) : not started (Black out)

　TWL v20.1.0 + Bootstrap v0.39.1 (DSiLL)
Mario Kart DS (JP) :  Freezes when multi-play is selected
Momotarou Dentetsu 20 Shuunen (JP) : Error when multi-play is selected
Momotarou Dentetsu Tokyo and Japan (JP) : Download play is possible, but wireless play is freeze
Momotarou Dentetsu World (JP) : Error when multi-play is selected

　TWL v20.1.0 + Bootstrap v0.39.1-fb3fb738 (DSi + DSiLL)
Mario Kart DS (JP) : Sometimes I can launch multiplay, but it doesn't work well. [ Communication error (Download play)，Do not recognize each other (Wireless Play)]
Momotarou Dentetsu 20 Shuunen (JP) : Good (?)
Momotarou Dentetsu Tokyo and Japan (JP) : Download play is possible, but wireless play is freeze
Momotarou Dentetsu World (JP) : Communication between DSi and DSiLL Communication was interrupted at the start of the battle (DSi side freezes)

For the time being, it is a report of malfunction in wireless play within the range that can be confirmed.
I think it's probably due to Bootstrap, so I'll get the logs in the near future.

**Comment by RocketRobz** [comment]
Try re-testing with VRAM boost turned off.

**Comment by RocketRobz** [comment]
MKDS doesn't freeze on my side when I select the multi-play option.

**Comment by KururinX** [comment]
Mario Kart DS (JP)
TWL : v20.2.1 , Bootstrap : v0.40.2 , VRAM Boost : OFF , DMA : ON

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/6512782/NDSBTSRP.LOG)

I tried other settings, but it freezes with multiplay selection.

**Comment by KururinX** [comment]
Momotarou Dentetsu 20 shuunen (JP)
DSi LL
TWL : v20.2.1 , Bootstrap : v0.40.2 , VRAM Boost : OFF , DMA : ON

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/6512836/NDSBTSRP.LOG)

not started. (white out)

**Comment by KururinX** [comment]
Momotarou Dentetsu Tokyo and Japan (JP)
DSi LL
TWL : v20.2.1 , Bootstrap : v0.40.2 , VRAM Boost : OFF , DMA : ON

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/6512893/NDSBTSRP.LOG)

Freezing when selecting download play (Japan)
I tried other settings, but the situation didn't change.

**Comment by KururinX** [comment]
Momotarou Dentetsu World (JP)
DSi LL
TWL : v20.2.1 , Bootstrap : v0.40.2 , VRAM Boost : OFF , DMA : ON

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/6512909/NDSBTSRP.LOG)

not started. (black out)
I tried other settings, but the situation didn't change.

**Comment by KururinX** [comment]
Tales Of Innocence (JP)
DSi LL
TWL : v20.2.1 , Bootstrap : v0.40.2 , VRAM Boost : OFF , DMA : ON

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/6513008/NDSBTSRP.LOG)

Can't connect to the other party in VS mode
I tried other settings, but the situation didn't change.

**Comment by KururinX** [comment]
Not being able to play online both download and wireless isn't a big deal for me as I don't have a companion. (:-\

However, malfunction in single play is a big problem.
In the Momotaro Dentetsu series, "Bootstrap v0.39.1-fb3fb738" seems to have no problem for the time being.

**Comment by EdEddED** [comment]
Going to jump in here and say I've been having the same problem in all my WFC and local wireless capable games - right when I was going to do a live stream showcasing the capabilities of it off 😅

Was about to create a new issue, but I'll just copy and paste my summary here instead.

**Your console: Nintendo DSi XL**
**Launch Method: MemoryPit (Nintendo DSi Camera) on Ver 1.4.5U** 
**Version used: Release Ver. 0.41.0** 
**Game tested/used/applicable:** ALL DS SOFTWARE, but tested with:
Clubhouse Games (US Ver., ATDE, Revision 1, MD5: D2E44B8770C71706A6C8255DDAC6847D)
Mario Kart DS (US Ver., AMCE, MD5: 8CBF438D5A7C0D9ACBE56A9B627CA6C5)
Nintendo WFC Configuration Tool (Bundled with all WFC Capable games)

**Expected Behavior:** For Local Wireless: The appropriate menu for wireless play should open up and function normally.
For WFC: The connection should either succed or fail, as appropriate for the system's current WFC configuration.
For Configuration tool: Connection tests should complete as appropriate, and when asked to scan for access points, It should actually scan for access points.
**Actual Behavior:** In Clubhouse Games, Entering the Local wireless menu stops the game from responding to input for 10-15 seconds, before erroring out with a "Communication Error".
In Mario Kart DS, Entering the multiplayer menu immediately crashes the game on a black screen and a repeating sound buffer.
In the WFC Configuration tool, selecting "Search for access point" softlocks the system in mid-transistion, and does not start searching for access points.
In ALL WiFi modes, the game/tool will not proceed past the "Connecting to Nintendo WFC/Testing Connection" Prompt, softlocking all games and the configuration tool as there is no way to cancel out of the screen.

### Steps to reproduce

Local Wireless:
1. Load nds-bootstrap via your method of choice, with a multiplayer-capable game. (in my case, it's with TwiLight Menu++, with the Memory pit exploit)
2. Enter a game mode which utilizes Wireless communications [In Clubhouse games: Multiplayer > Local Wireless. In Mario Kart DS, Multiplayer on the Main Menu]

WFC Configuration tool, Search for access points:
1. Load nds-bootstrap with a WFC Capable game.
2. Find and enter the game's WFC Configuration options [CHG: Multiplayer  > Nintendo WFC  > WFC Settings. MKDS: [Nintendo WFC > Nintendo WFC Settings]
3. Select an empty configuration slot. Erase a slot if you need to.
4. Select "Search for Access Point"

WFC, Connectivity
1. Load nds-bootstrap with a WFC Capable game.
2. Find and enter the game's WFC mode  [CHG: Multiplayer  > Nintendo WFC  > Wi-Fi Battle. MKDS: [Nintendo WFC > Nintendo WFC Match]
3. Select Yes to connect to Nintendo WFC.
OR
A. Load nds-bootstrap with a WFC Capable game.
B. Find and enter the game's WFC Configuration options [CHG: Multiplayer  > Nintendo WFC  > WFC Settings. MKDS: [Nintendo WFC > Nintendo WFC Settings]
C. Select a used configuration slot (Create one via DSi Settings if you need to).
D. Select Connection Test.

Contents of nds-bootstrap.ini
[NDS-BOOTSTRAP]
DEBUG = 1
LOGGING = 1
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 0
PRECISE_VOLUME_CONTROL = 0
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 284
NDS_PATH = sd:/ROMs/owned/Clubhouse Games (USA) (En,Fr,De,Es,It) (Rev 1).nds
SAV_PATH = sd:/ROMs/owned/saves/Clubhouse Games (USA) (En,Fr,De,Es,It) (Rev 1).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = -2
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
CARD_READ_DMA = 0
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0


### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/6604778/NDSBTSRP.LOG)

### Other notes
This was all working the last time I was playing with it and getting my configurations ready to roll.
I've tried resetting my Twilight menu++ settings (which required manually deleting the INI file as the Boot last game shortcut overrides the reset settings shortcut), removing and recreating WFC configurations, and have even updated both it and nds-bootstrap to the latest versions. This issue does not affect the 3DS, as it can still connect and interact with WiFi just fine even after the update. My DSi's wifi antenna is also functioning as it should, as a Retail DS cart launched via the DSi menu and the DSi system settings all function normally.

**Comment by RocketRobz** [comment]
The wireless issues have been fixed for a while now.
I'm pretty sure the interruption issues we're caused by the card DMA implementation then.
