### ISSUE TITLE
pokemon gold not working

### ISSUE THREAD

**Issue by champi12** [DS-Homebrew/nds-bootstrap#1182]
In these latest updates, the gold pokemon throws me a black screen, but it works without problems in the v18.4.0 version. Do you know what the error is here friend?
It should be noted that I have already updated to the latest version as of today

**Comment by RocketRobz** [comment]
The crash is caused by either IR being disabled, or no DS game inserted into Slot-1.
With Slot-1 being disabled to save on power, that's why it crashes.
It's preferable to improve the AP-fix to remove the Slot-1 check, rather than re-enabling Slot-1 to use up battery for something that isn't in use.

**Comment by Ryper-maximoft** [comment]
mmm so the current ap fix doesnt help? not sure if there is a new fix yet

**Comment by champi12** [comment]
Good friend I already tried several versions of the game and all the
English versions work without problems but differently the Spanish
versions none works freezes when starting the game this patched or not
but if I reinstall an old version of Twilight specifically the version
v18.4.0 the game It works normally without any errors, could something
be done to repair it ??? sorry my english i use google translator
