### ISSUE TITLE
Mega Man Star Force 2: Zerker x Ninja freezes when entering Whazzap

### ISSUE THREAD

**Issue by blowhi** [DS-Homebrew/nds-bootstrap#1335]
**Your console:** New 3DS

**Launch Method:** SD Card

**Version used:** v0.53.2

**Game tested/used/applicable:** Mega Man Star Force 2: Zerker x Ninja
MD5: E38D80598AEDFBBD7E292DAEB513AFAE
SHA-1: 97C7FBAEB9C22B9B588869C6A7518C7940E17AB8

**Expected Behavior:** game doesn't freeze

**Actual Behavior:** game freezes 

### Steps to reproduce
1. Enter the green portal in Whazzap's sky wave

### nds-bootstrap.ini

> [NDS-BOOTSTRAP]
NDS_PATH = sd:/Roms/DS/Mega Man Star Force 2 - Zerker x Ninja (USA).nds
SAV_PATH = sd:/Roms/DS/saves/Mega Man Star Force 2 - Zerker x Ninja (USA).sav
BOOST_CPU = 0
DEBUG = 0
LOCK_ARM9_SCFG_EXT = 0
BOOST_VRAM = 0
DSI_MODE = 1
CACHE_FAT_TABLE = 0
LANGUAGE = -1
REGION = -2
AP_FIX_PATH =
CARD_READ_DMA = 0
ASYNC_CARD_READ = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CONSOLE_MODEL = 2
RAM_DRIVE_PATH = sd:/null.img
EXTENDED_MEMORY = 0
FORCE_SLEEP_PATCH = 0
LOGGING = 1
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
PRECISE_VOLUME_CONTROL = 0
MACRO_MODE = 0
SOUND_FREQ = 1
SDNAND = 0
HOTKEY = 284
GUI_LANGUAGE = en
SWI_HALT_HOOK = 0
USE_ROM_REGION = 1
B4DS_MODE = 0

### Logs

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/7808333/NDSBTSRP.LOG)

### Other notes
L+Down+Select restarts TwilightMenu

**Comment by RocketRobz** [comment]
Try adjusting some setting in the per-game settings menu (opened by pressing Y in the TWLMenu++ Settings).

**Comment by blowhi** [comment]
got it to work after running the game in DSi mode

**Comment by Kaisaan** [comment]
Well since a fix has been found (running the game in DSi Mode), this issue will be closed now.

**Comment by Squall-Leonhart** [comment]
thats not a fix, its not a dsi game.

**Comment by Volt790** [comment]
Hello, I saw this & wanted to add some info. I got to Whazzap & it froze as expected, but I decided to play ahead on an emulator to see if it was only just the first time cutscene. I'm currently up to Solo attacking Bud & the game has still frozen multiple times. I boot up in Whazzap during thr Ginger Beef ingredient hunt, it just freezes. I boot it up on the Sky Wave during the Solo attack to go into Whazzap & the danger music plays but the screens are stuck on white.
It seems like the game just crashes in general in Whazzap. Dunno if it happens in Saurian but I'm tempted to switch...

**Comment by Kaisaan** [comment]
This issue does not happen to me. Tested on a N3DS XL with nds-bootstrap version 0.63.2 and TWiLight Menu++ version 25.2.1 with all per-game options set to Default. Also tested this with the [Not Quite DX patch](https://forums.therockmanexezone.com/mega-man-star-force-2-not-quite-dx-t16660.html). Can somebody else also confirm that this issue is fixed?

**Comment by RocketRobz** [comment]
Seeing as it's a ROM that gets pre-loaded into RAM, it's safe to assume that it's indeed fixed (likely by v0.63.1).

**Comment by Volt790** [comment]
Wanted to come back to this to say: I finally got it working. I believe the issue was updating nds-bootstrap via Universal Updater. It SAYS V0.63.2, but in the TWiLight Menu++ Settings, it said V0.57.0. After manually updating the files via the Github release, it said V0.63.2 in the settings & the game loaded Whazzap when I entered.
