### ISSUE TITLE
Multiplayer doesn't work

### ISSUE THREAD

**Issue by metehan5327** [DS-Homebrew/nds-bootstrap#1358]
Hey,

The local multiplayer doesnt work on my new 3ds for my nds games like mario party ds or jump ultimate stars. When me and my friends go into local mode on any nds game we cant find each others 3ds. 

Thanks for the help and have a nice day my friends.

**Comment by metehan5327** [comment]
I dont have twl menu i launch it over the nds forwarder pack

**Comment by RocketRobz** [comment]
Make sure Wireless is turned on in the console.

**Comment by CakeGamingOfficial** [comment]
I'm having the same issue. I just checked TWLMenu++ and my wifi is turned on. I'm not even getting a local signal showing.

**Comment by metehan5327** [comment]
The wireless is turned on and connected sir but when i go into the game it loses the connection

**Comment by CakeGamingOfficial** [comment]
> I'm having the same issue. I just checked TWLMenu++ and my wifi is turned on. I'm not even getting a local signal showing.

I was able to fix the issue by installing the TWLMenu++ and launching it. I then hovered over Mario Kart DS and pressed y to go into the in game settings. I then turned off "Card Read DMA" and it fixed it with download play.

**Comment by ds17f** [comment]
Can we re-open this?  I'm seeing the same problem.  I've asked about this on reddit and the standard advice is to make sure that WiFi is turned on.  Wifi is on on my 3DS, and I'm sure it's on in TWLMenu++.  I've tried using forwarders, and I've tried the setting the @metehan5327 mentioned above.  Nothing seems to make a difference.

In the case of `New SMB`, I'm able to go to the multiplayer and it eventually cancels out saying that the connection was interrupted.  I never see the little spinning red fireball that I see on my DSi.  `Mario Kart DS` hangs as soon as I start up the multiplayer with audio stalled and making noise.  `Zelda Legend of the 4 Swords Anniversary Edition` never brings up the multiplayer menu, effectively freezing like `MKDS` does.

I've tried installing from `Universal Updater` and from `GitHub` as well.  Neither seems to make a difference, the outcome is the same.  I'm confident that the roms are good, they work fine on the DSi.

I'd be happy to post logs, or otherwise provide anything I can to support this.  The feedback I get elsewhere is that this SHOULD work, but it's pretty clear to me that something is wrong.  I'm moderately confident that the console is setup correctly, but it's possible I missed something along the way.

**Comment by NormanSReinhart** [comment]
Have you tried turning off card read dma?

**Comment by CakeGamingOfficial** [comment]
Have you tried turning off card read dma?

**Comment by RocketRobz** [comment]
Card read DMA isn't the issue.

@ds17f Sounds like your 3DS WiFi card is either broken or not seated correctly, despite it working fine in 3DS mode.

**Comment by ds17f** [comment]
Interesting. I guess I'll open it up and reseat it.

**Comment by ds17f** [comment]
I tried reseating the wifi card and it does not appear to change the outcomes. I ordered a replacement card for about $8 on Amazon. It will be here tomorrow and I'll see if it makes a difference. Will follow up here either way. 

Thanks @RocketRobz for jumping in.

**Comment by ds17f** [comment]
Woohoo! So I pulled the wifi board and cleaned the contacts with isopropyl alcohol and then reseated it. And it worked! Hardware it was! Yay!!!
