### ISSUE TITLE
Every Game  nds-bootstrap (stable) not found error 1

### ISSUE THREAD

**Issue by Maximoose04** [DS-Homebrew/nds-bootstrap#1389]
**NDSI XL**

**Mario Kart DS**

**Version used:**

**Game tested/used/applicable:**

**Expected Behavior:**

**Actual Behavior:**

### Steps to reproduce
1. 
2. 
3.

**Comment by Allinxter** [comment]
Make sure the file `nds-bootstrap-release.nds` exists in the folder `sd:\_nds\`.

Also, please follow the indications on the issue template.

**Comment by Maximoose04** [comment]
I looked and it doesnt exist, even anywhere in the SD card, how can i restart from scratch? I think I know what I did wrong I donwload HiyaCFW instead of Twilight since I have over 4Go of space

**Comment by Allinxter** [comment]
Follow this https://wiki.ds-homebrew.com/twilightmenu/installing-dsi.
Where did you get that you had to install hiya instead of TWiLight if your SD card is over 4GB?
For future reference, read the [official guide](https://dsi.cfw.guide/) or the [wiki](https://wiki.ds-homebrew.com/) for trusted info.

**Comment by Maximoose04** [comment]
Oh wait I think I misunderstood what was read, I understood if it was over 4Gb i had to use twilight menu but I think it said if it was under 4gb, am I wrong?

**Comment by Allinxter** [comment]
TWiLight can be used with any size of SD card (up to 4TB, technically), as long as it's correctly formatted.
