### ISSUE TITLE
manual character set encoding question

### ISSUE THREAD

**Issue by clach04** [DS-Homebrew/nds-bootstrap#1398]
**Your console:**

NA

**Launch Method:**

NA

**Version used:**

https://github.com/DS-Homebrew/nds-bootstrap/releases/tag/v0.56.0

**Game tested/used/applicable:**

NA

**Expected Behavior:**

@Epicpkmn11 What character set encoding should be used for the text based manuals that was added in #831 ?

The code appears to not do any processing when reading (I'm guessing it's what ever character set is configured for the in game menu?)

Thanks for implementing this! I'm looking forward to playing with this when I get chance 👍 

**Actual Behavior:**

NA

### Steps to reproduce

NA

### nds-bootstrap.ini

NA
### Logs

NA
### Other notes

NA

**Comment by Epicpkmn11** [comment]
It just uses [the same encoding as the menu text](https://github.com/DS-Homebrew/nds-bootstrap/blob/master/retail/arm9/source/text.cpp#L9-L72), for Latin, Cyrillic, Greek, and Hebrew it's slightly altered versions of Windows 1252, 1251, 1253, and 1255 respectively, but for the other languages it's something weird since I want to only use an 8-bit encoding in game to save space but obviously you can't fit a real CJK encoding in 8 bits. Arabic is a complete font, but iirc I couldn't find any common encoding that used presentation forms well enough to be worth matching.

The [font pages](https://github.com/DS-Homebrew/nds-bootstrap/tree/master/xcf/igm_font) and the above linked mappings can be altered if needed (ex. I could add in some of the punctuation marks I left out) and it won't break the in-game menu text since that's converted from Unicode automatically, it's not really practical to go beyond 8 bit encodings though so unfortunately I don't expect CJK manuals to be practically possible.

**Comment by clach04** [comment]
Makes sense, I was guessing that might be the case. Probably worth recommending 7-bit ASCII, and that mileage-may-vary with 8-bitin the docs/FAQ.

Thanks again for working on the feature, I'm expecting to make use of this once I get setup :-)
