### ISSUE TITLE
Option to flip screen orientation horizontally

### ISSUE THREAD

**Issue by kokoropaint** [DS-Homebrew/nds-bootstrap#1457]
Could there be a way to flip the screen horizontally? This is a niche feature but since you can switch the top/bottom screens I was wondering if it'd be hard to add.

I picked up a DSi recently to play (alongside other games) Love Plus, which plays vertically, but I'm left-handed and there's no way to flip the screen around ingame so everything feels really cramped. :(

**Comment by Epicpkmn11** [comment]
This would probably be best handled as a cheat code for that specific game. I think it should be possible since the DS has hardware rotation, however it might be tricky depending on how it works, if everything is 3D then it should be quite easy where 2D would be trickier. Assuming the 3D layer can be rotated, I think it can.

There's also the matter of touch input, that should be possible too but it's probably rather game specific.
