### ISSUE TITLE
sm64 dsi port support?

### ISSUE THREAD

**Issue by RonyxDumb** [DS-Homebrew/nds-bootstrap#1502]
I was thinking, since nds-bootstrap also runs on flashcards (certainly with lesser compatibility), is there a way to run the SM64 Port for NDS(i) on flashcards?

**Comment by RonyxDumb** [comment]
I'm using Twilight Menu (which uses Nds-bootstrap) for flashcards (specifically, R4)

**Comment by RocketRobz** [comment]
1. This is out of scope for nds-bootstrap. Support for original DS consoles would have to be implemented in the port itself.
2. SM64DSi is recent homebrew, so nds-bootstrap is not used to run it.

**Comment by NightScript370** [comment]
What nds-bootstrap does is just patch retail ROMs's SDK functions to read/write to the SD card. Unfortunately, SM64DSi is a homebrew which would not be affected by this, simply because it doesn't use the SDK.
Furthermore, the only reason why the regular DSiWare ROMs work is because they didn't utilize their extra memory very well, whereas SM64DSi utilizes it HEAVILY, with the entire ROM being loaded.

Suffice it to say, SM64DSi is not something we could support.

**Comment by RonyxDumb** [comment]
Oke, thanks
