### ISSUE TITLE
Exiting Bootstrap menu crashes game

### ISSUE THREAD

**Issue by ZaditzWarrior** [DS-Homebrew/nds-bootstrap#1653]
### Game Console(s) used

- [ ] Nintendo DS
- [ ] Nintendo DS Lite
- [X] Nintendo DSi
- [ ] Nintendo DSi XL/LL
- [ ] Nintendo 3DS
- [ ] Nintendo 3DS XL/LL
- [ ] New Nintendo 3DS XL/LL
- [ ] Nintendo 2DS
- [ ] New Nintendo 2DS XL/LL

### Launch Method

Game launches from SD card on DSi console

### Version used

Release

### Game tested/used/applicable

Game title:
-Transformers ROTF Autobots
-Transformers ROTF Decpticons 

### Expected Behavior

The in game menu should open displaying a list of options and exiting it should return to the game.

### Actual Behavior

The in game menu opened as normal but upon exiting the menu the game freezes requiring the console to be restarted to recover 

### Steps to reproduce

Launch game (default setting) then open in game menu and then exit it game should crash

### nds-bootstrap.ini

File not available 

### Logs

Not available 

### Will you be available for future issues and/or replies?

Yes

**Comment by amitkulk123** [comment]
I was running into a similar issue on N3DS XL where opening and closing the menu randomly crashes the game: https://github.com/DS-Homebrew/nds-bootstrap/issues/1581

**Comment by iromegane** [comment]
Hi, I have the latest version as of right now (v26.3.1). 

I'm using the in-game menu option, and it often crashes the system to shut down or error screen. Apologies if this isn't about the general twilight in-game menu.

I'm using a flash cart(Acekard 2i). I wanted to take screenshots but the menu for it is constantly crashing the game(Pokemon Mystery Dungeon Blue Rescue Team).

**Comment by ZaditzWarrior** [comment]
It shouldn’t crash in Pokémon blue rescue team perhaps you aren’t using default settings

**Comment by iromegane** [comment]
Thanks for the heads up, I haven't really messed with any settings, but the textbook in Pokemon Rescue just likes to be a bit weird in screenshot mode with no good options

I also managed to get an error screen with DQVI while screenshotting; I have no clue, honestly. It might just be the side effect of using a flash card Twilight++ install on a DSlite instead of a 3DS with more memory resources, perhaps.

![screenshot01](https://github.com/DS-Homebrew/nds-bootstrap/assets/152935496/f62b8c01-4f34-4c84-8612-320ff9d14332)
![screenshot16](https://github.com/DS-Homebrew/nds-bootstrap/assets/152935496/1fdcd0c6-b74a-4054-9b7b-d7cae1b4bfed)
