### ISSUE TITLE
NDS game audio split

### ISSUE THREAD

**Issue by Zetaro666** [DS-Homebrew/nds-bootstrap#1723]
I noticed that while playing that the audio for the games is split. The left speaker plays mainly music while the right plays mainly sounds like attacks, screams, ect. I've looked all over to see if there was some audio settings I could adjust but I haven't found any way to fix this. 

Is anyone else getting this issue? I'm somewhat certain it's a twilight menu++ issue but don't know if it is or not.

**Comment by RocketRobz** [comment]
Which games is this happening in? Because this is the first time I've heard of this happening.

**Comment by Zetaro666** [comment]
It's happening to any game I play tbh. I've noticed with Pokemon SoulSilver that the left speaker will play the sound effects of my pokemon while the right plays the sound effects of the opponents. 

It's almost like the audio is formated in a certain way. Like back in the day, tons of songs I downloaded would have this effect. One guitar solo would play in one ear and the right would play another.

**Comment by RocketRobz** [comment]
> It's happening to any NDS game I play tbh. I've noticed with Pokemon SoulSilver that the left speaker will play the sound effects of my pokemon while the right plays the sound effects of the opponents.
>
> It's almost like the audio is formated in a certain way. Like back in the day, tons of songs I downloaded would have this effect. One guitar solo would play in the left ear and the right would play another.

That sounds like proper usage of the speakers to me then, because your Pokemon is on the left-side of the screen, and the opponent's Pokemon is on the right-side of the screen.
Sounds like which sounds play on which speaker is dependant on both the game and area of the game then.

That said, it is not an issue with TWLMenu++ or nds-bootstrap, and could also happen on the original cartridge.
