### ISSUE TITLE
multiplayer not working

### ISSUE THREAD

**Issue by carterminer** [DS-Homebrew/nds-bootstrap#869]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
-   Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

-   Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

-   Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

-   SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

animal crossing wild world

the game will not work in multiplayer it gives multiplayer error on both sides

**Comment by SleepyLark** [comment]
Possibly related to #794?  I haven't played the game much so I wouldn't know until I test it myself

**Comment by dswarez** [comment]
My DSi LL freezes in **any** multiplayer mode (Tetris DS, Mario Slam Basketball, Sonic Colors...). With the exact same SD (last boostrap release and Twilight), it works on my friend's Dsi .

We both have 1.4.5 J firmware (it didn't work on 1.4 J either).

Isn't the hardware of the DSi and DSi LL is supposed to be the same ?

**Comment by RocketRobz** [comment]
Do both consoles boot TWLMenu++ thru Unlaunch?

**Comment by dswarez** [comment]
I guess so, I am using the memoryPit exploit without HiyaCFW.

We swap the same card and it behaves differently on both consoles.

**Comment by RocketRobz** [comment]
So are you using Memory Pit or Unlaunch to boot TWLMenu++?

**Comment by dswarez** [comment]
Sorry, we are using Memory Pit

**Comment by RocketRobz** [comment]
You need to use Unlaunch to boot TWLMenu++ on both consoles for Multiplayer to work.

**Comment by dswarez** [comment]
I see, thanks for the quick feedback!  
Is it a technical limitation or something that might be implemented in the future for the Memory Pit ?

**Comment by RocketRobz** [comment]
We don't plan on improving support for DSiWarehax exploits such as Memory Pit.

**Comment by dswarez** [comment]
Alright. Thanks for the great work RocketRobz. 

I can't believe how easy it is to play pixel perfect games from so many systems on my DSi. This community is amazing!

**Comment by dswarez** [comment]
So, a little bit of feedback. I ended up installing Unlaunch on both japanese Dsi and Dsi LL, latest TWLMenu++. Although we experience network errors at times, we managed to have it work. 

**But**, somehow the DSi LL will never accept the be the host. It would freeze or get disconnected.

**Comment by NightYoshi370** [comment]
Is this single cart multiplayer or dual-cart multiplayer?

**Comment by dswarez** [comment]
It's dual-cart.

**Comment by popy2k14** [comment]
same issue here with two DSI XL (1.4.5E FW), both with unlaunch v2.0 and newest TWL++ 15.1.1 and newest nds-bootstrap 0.35.1.

One doesn't find the other on multicart game "rummikub". But one DSI XL works with an DS lite + flashcard m3 ds real.

Is there anything i can do do help to find/solve the issue?

**Comment by SleepyLark** [comment]
> Could this be an hardware defect? Maybe repalcing the wifi board worth it?
Is there anything i can do do help to find/solve the issue?

I doubt it's a hardware defect, try changing the CPU speed and keep retrying, I was having trouble playing Mario Kart DS on multi-card but was later able to get it to work after a while.

**Comment by popy2k14** [comment]
Swapped the wifi boards and issue stayed on the DSI XL which had it before. Other DSI with swapped wifi board works fine again. So no hardware issue on the wifi board. Already tried various cpu settings without luck. any other hints?

**Comment by popy2k14** [comment]
Something weired happend. I have put the SD card from the OK DSI into the not ok DSI and hell yeah the wifi direct play is working to the DS lite at least, seems to be some setup issue!?

Trying a few things like copyng stuff from one sd card to the other....
Keep you updated, thx

**Comment by popy2k14** [comment]
Hey guys, finally fixed the issue.

Have tried teh following:

- deleted all the contents from the non working sd card -> copied over the contents from the working -> issue not solved
- formated the non working sd card -> copied over the contents from the working -> issue not solved
- cloned the working sd card to the non working wioth win32diskimager -> **success multiplayer is working!?!?!?!**
- restored all the contents of the non working sd card (made a backup before) to the new cloned and overwriting the contents , except _nds folder (because of hija cfw, nand backup and so on) -> **success multiplayer working as before**

made now a backup of both with win32diskimager and keep those just to be sure.
The before not working sd card was an 32gb microsd card and the working one an 16gb one. Now the partiontable also was copied -> now i have just 16gb on the 32gb card. I dont want to expand the partition and mess with the partition table again and mess something up. for me its a ok solution,

any hints what the issue could be that the sdcard (format!?) has an impact on the multiplayer function of rummikub game?

**Comment by RocketRobz** [comment]
Same as #985, so closing.
