### ISSUE TITLE
Dragon Quest IX US white screen.

### ISSUE THREAD

**Issue by Rodokami** [DS-Homebrew/nds-bootstrap#931]
**Your console:** New 2DS
**Launch Method:** Luma 10.1.3 - TWiLight Menu++. v15.0.0 - SD
**Version used:** Release nds-bootstrap v0.35.0.
**Game tested/used/applicable:** Dragon Quest IX: Sentinels of the Starry Skies USA
**Expected Behavior:** Game starts normally
**Actual Behavior:** After the nds bootstrap loading screen the game gives a white screen.

### Steps to reproduce
Just try to start the game normally 

### Other notes
Eur version of the game works fine.

**Comment by RocketRobz** [comment]
Try turning off heap shrink.

**Comment by Rodokami** [comment]
Still the same.

**Comment by RocketRobz** [comment]
Are cheats turned on?

**Comment by Rodokami** [comment]
Nope. I even didn't download usrcheat.dat.

**Comment by Salavaro** [comment]
I also had this issue before, what fixed it for me was applying the AP patch to the ROM with DS-Scene Rom Tool. I don't know if you're still having this issue but give it a try. It was also happening to me on DQMJ2 and the same solution worked. Note that I use a N3DS XL, but otherwise still the latest releases of Twilight, boostrap and Luma CFW.

**Comment by RocketRobz** [comment]
Considering that the included patch is based on the ROM patched by DS-Scene ROM Tool, I don't see why this would happen.
