### ISSUE TITLE
Pokémon Black 2 loads really slowly on SD cards with low cluster sizes

### ISSUE THREAD

**Issue by Epicpkmn11** [DS-Homebrew/nds-bootstrap#965]
**Your console:** DSi (U)
**Launch Method:** Unlaunch v2.0, TWiLight Menu++ v15.2.0
**Version used:** Release v0.35.1, v0.34.0
**Game tested/used/applicable:** Pokémon Black Version 2 (U) (SHA1: e51e6dfb8678a3d19dcd2a10691b96a569ca0abb (GM9i full dump))

**Expected Behavior:** Game loads at a decent speed
**Actual Behavior:** Starting with v0.35.0, Pokémon Black 2 is basically unplayable, I haven't tested many other games so its likely others are affected too, but Mario Kart DS still ran at a good speed. I believe Pokémon Black 2 is using a large streamed audio file at the title screen where its especially awful ([Video](https://cdn.discordapp.com/attachments/332961165829210117/722014264490983434/KVID0110.mp4)). In v0.34.0 Pokémon Black 2 runs runs well on this card.

### Steps to reproduce

- Format your SD card using 4KB cluster size (Other low ones are probably bad too, I used 4KB. 32KB on a similar card runs fine)
- Run Pokémon Black 2 (probably other games too)
- It took ~10 minutes for the game to even load for me, then once it did it was unplayably slow

### Logs

I didn't have logging on and it takes ***10 minutes*** to load so I'm not going to launch it again right now, I can if that would be helpful though.

### Other notes

I used some absolute garbage class 2 cards, so while I think this affects any card (stgiga#7394 was using class 10 to similar results), its probably extra bad on my cards. I tried Mario Kart DS too and it ran fine, so not all games appear to be affected, though I wouldn't be surprised if more were.

**Comment by sentogiga** [comment]
nocash's Magic Floor (written in ARM assembly) is also broken in 0.35.x but works fine in 0.34.0. Nocash's Magic Floor uses the PSG functions of the DS sound chip as well as doing it in a more direct way than most DS games do. Pokemon B1W1 don't stream audio at all and have no strm data, but in B2 the cutscene immediately after Game Freak shooting star animation has a Nintendo format PCM stream rarely used on the DS. If the cutscene finishes or skips when bugged, it will soft crash with an ear-splitting sound if it gets to the 3D part with the logo, which doesn't use streaming of PCM. These two wildly different games are good torture tests for NDS_bootstrap because they take advantage of the DS hardware in specific ways. Magic Floor doesn't have a file system and it is assembly and it uses the PSG in the DS sound chip in a more direct way. Pokemon B2 is a gigantic DSi-enhanced game (even though the actual data is only slightly more than BW1's 256MiB cartridge, which means that the devs didn't use that much of the 512MiB space beyond the original 256MiB that BW1 used) As a half-relevant aside, the patching stuff used for WiFi patches before nds_constraint had a problem with Japanese Black 2 in particular, which has an insane amount of URLs in it, likely due to involvement with quite a lot of the Japanese Pokemon Global Link site from what I can gather. The version of Black 2 that I (stgiga) found the bug on is the US version of the game. This could very well mean that the Japanese one could very easily glitch more if it's a matter of size. So testing JP B2 in particular is also a wise idea. B2W2 are SDK5 games, so testing other significant SDK5 games would be wise.

**Comment by Hawkeye1005** [comment]
I was also having this problem until a few days ago when I reformatted my SD card to 32kb clusters.

**Comment by sentogiga** [comment]
The point is that cards that aren't formatted with 32kib used to work before 0.35.x, which means that there is a regression involved.

**Comment by NightYoshi370** [comment]
https://github.com/ahezard/nds-bootstrap/compare/v0.34.0...v0.35.0#diff-ea1b35892eef97d4001b3f05858b35bc
Here's a comparison between 0.34.0 and 0.35.0. I linked directly to the nds-bootstrap retail area, so you wouldn't need to scroll through the list

**Comment by RocketRobz** [comment]
See if commit 646eb8cc fixes this.

**Comment by Epicpkmn11** [comment]
I just tested on 646eb8c and a31f6d4, 
On 646eb8c it was a white screen for around 8 mins then switched to black top white bottom and stayed like that for like 10 more mins so I turned it off.
a31f6d4 took like 3 mins to get to the black and white screens, another few mins and the intros finally started playing with similar performance to v0.35.1. Here's the log from a31f6d4: [NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/4789239/NDSBTSRP.LOG)

By comparison v0.34.0 loads in about 3 minutes, here's its log [NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/4789258/NDSBTSRP.LOG)

**Comment by zipplet** [comment]
Confirmed this is definitely a sector size issue with the latest nds-bootstrap.
Pokemon White 2 was frozen on a white screen forever.
Backed up my SD card, reformatted with 32KB cluster size and restored the files. The problem is gone and the game runs perfectly.

**Comment by zipplet** [comment]
I also noticed 32KB cluster size improves the loading performance of Twilightmenu in general so maybe this needs to be checked out for that project too? Should I open an issue?

**Comment by piratesephiroth** [comment]
that's the recommended cluster size for use with 3DS homebrews

**Comment by zipplet** [comment]
> that's the recommended cluster size for use with 3DS homebrews

Thanks @piratesephiroth I didn't know that - I'll keep this in mind going forward. It might be good if the various guides mention this somewhere, but I know that isn't the responsibility of the devs of nds-bootstrap.

**Comment by piratesephiroth** [comment]
3ds.hacks.guide recommends that size, near the end of the initial page

**Comment by zipplet** [comment]
Awesome, I did my cfw a couple of years ago and probably missed that - oops. I can't see it on the DSi guide though.
Thanks for taking your time to respond, for all the devs hard work on nds-bootstrap. The project has come a long way in the past couple of years.

**Comment by NightYoshi370** [comment]
The DSi guide has it in the SD card set-up page

**Comment by zipplet** [comment]
I'm clearly blind - just took another look and amended my comment.
I think the reason the above issue occurs ^ is because people tend to use the windows formatter "blind" without double checking. User error clearly, but I wonder if there is anything that can be done to stop it causing issues like this one from being opened.

Maybe have a popup message under the "Loading...." when using the wrong cluster size?

**Comment by lifehackerhansol** [comment]
This issue is reproducible even with flashcarts on their original kernel. The 32KB cluster size thing goes way back before DSi homebrew was a thing.

**Comment by Epicpkmn11** [comment]
> This issue is reproducible even with flashcarts on their original kernel. The 32KB cluster size thing goes way back before DSi homebrew was a thing.

This didn't happen prior to v0.35.0 though so it should be possible to fix. I'm not sure what exactly changed, but might be worth having a look what changed there and see if there's anything bugged or so.
